### ISSUE TITLE
Locale file don't load when setLocale(), cache issue ?

### ISSUE THREAD

**Issue by stfr** [zerospam/laravel-gettext#26]
Hello,
First of all, thanks for this package ! :)

In my project, locale is changed by a custom LocaleMiddleware, which take the lang from the URL ( /en/my-page), and change it with `LaravelGetText::setLocale()` + `App::setLocale()`

But it doesn't work perfectly. This is what happens :
- load page in French(default language) (`/fr/ma-page`) :  French  file is loaded
- change to Spanish (`/es/mi-pagina`): Spanish file is loaded
- F5 on `/es/mi-pagina` : French is back (but `App::getLocale()` & `LaravelGettext::getLocale()` returns Spanish)
- clear:cache, then refresh : Spanish is back. 

So, it seems to be something related to the cache.
I tried lot of things, but i'm running out of ideas.  Someone have ever seen this case ?

I have found an ugly solution: extend the Symfony Translator to put the `loadLocaleFile` method as public, in order to call it at the end of my LocaleMiddleware, after the `LaravelGettext::setLocale()` ...

**Comment by Sunvers** [comment]
Hi, I have the same problem. How do you call `loadLocaleFile` on your middleware? How do you initialise the extended translator/ get the translator reference?

**Comment by stfr** [comment]
It's been a while, but I think we added this line  in our custom Locale Middleware which define locale from the url :

```php
// Set locale and refresh locale file
LaravelGettext::getTranslator()->setLocale($locale);
```

it will directly force the locale in the translator Class, which refresh the cache.

**Comment by Sunvers** [comment]
It works! I used `LaravelGettext::setLocale($sessionLocale)`  and these resource file problem drove me crazy...

Many many thanks!
