### ISSUE TITLE
/src/Xinax/LaravelGettext/FileSystem.php:219 - mkdir(): No such file or directory

### ISSUE THREAD

**Issue by marcth** [zerospam/laravel-gettext#32]
When issuing `php artisan gettext:create`, the following error occurs:
```
/var/www/vendor/belphemur/laravel-gettext/src/Xinax/LaravelGettext/FileSystem.php:219 -
mkdir(): No such file or directory
```
This occurs when the path specified by `translations-path` (e.g. '`../resources/non-existent-dir`') in `config/laravel-gettext.php` does not exist.

**Comment by devuniverse** [comment]
The vendor name's changed to zerospam from belphemur . Could be the cause

**Comment by Fortune-Favors-Bold** [comment]
@devuniverse Is right, this project went from private to organization project.

Make sure you update to the latest version.
