### ISSUE TITLE
Any plan to add support for Laravel 6.0?

### ISSUE THREAD

**Issue by daveatpeta** [zerospam/laravel-gettext#37]
Any plan to add support for Laravel 6.0?

Is there enough significant changes to have to change the code or it's possible to simply add 6.0 to the composer.json file?

https://github.com/zerospam/laravel-gettext/blob/master/composer.json

Regards,

**Comment by Mxrck** [comment]
Laravel 6 is released now, but this package is not compatible

@daveatpeta have you tried your solution?

**Comment by CedNet** [comment]
My PR make it work. But it fails CI test due to tests not compatible with latest Laravel testing framework. Might spend time fixing it later today.

**Comment by daveatpeta** [comment]
Shouldn't the public function now be a protected function?

https://github.com/zerospam/laravel-gettext/blob/master/tests/unit/LaravelGettextTest.php

public function setUp()
->
protected function setUp()

**Comment by daveatpeta** [comment]
Thanks CedNet,

I added a Pull Request from my fork.
https://github.com/zerospam/laravel-gettext/pull/39

**Comment by WimDeMeester** [comment]
Also looking forward to a laravel 6 version!

**Comment by frofrik** [comment]
#39 is merged to the master branch, but no new release?

**Comment by WimDeMeester** [comment]
Can anyone test and merge the pull request please? It is the only package in my project that still needs to be updated for Laravel 6.

**Comment by WimDeMeester** [comment]
I have installed the latest source code manually in my laravel project. It works without problems in Laravel 6.

**Comment by devuniverse** [comment]
@WimDeMeester Could you please provide some guidance to do the same? I am stuck with this and I wish the maintainers could look into this.

**Comment by WimDeMeester** [comment]
@devuniverse , this is what I did: 

+ I removed the package using 

`composer remove zerospam/laravel-gettext`

+ I have checked out a fork of the latest version of this repository using 

`git clone https://github.com/WimDeMeester/laravel-gettext.git`

+ I add a local repository to the composer configuration, using 

`composer config repositories.local '{"type": "path", "url": "../laravel-gettext"}' --file composer.json`

(the url should point to the location where the checked out code is available)

+ I adapted the name of the package by changing to

`    "name": "wimdemeester/laravel-gettext",`

in ../laravel-gettext/composer.json

+ I installed the local version of the package using

`composer require wimdemeester/laravel-gettext`

+ After that, I could update to version 6 of laravel.

**Comment by frofrik** [comment]
In composer.json you can also just set the version to master.

**Comment by WimDeMeester** [comment]
Indeed! 

`composer require zerospam/laravel-gettext:master`

is a much cleaner solution!

**Comment by devuniverse** [comment]
@frofrik @WimDeMeester You guys are the best there is! Very much appreciated, because I have a few projects that depend on this package but I am always worried about the maintainability long term.

**Comment by philippe-bourdeau** [comment]
Hello guys, I haven't had much time to look into this and test with Laravel 6.0 (at the moment for our business case we are still comfortable with 5.9) but I'm following the discussion.

If master is working as expected, i'll just tag it and release so you can stick to semantic versioning instead of refering to master; in the mean time I will not merge anything in master so it's fine for now but in the long run it is not very reliable.

**Comment by WimDeMeester** [comment]
@philippe-bourdeau Works fine for me in Laravel 6.0

**Comment by devuniverse** [comment]
> Hello guys, I haven't had much time to look into this and test with Laravel 6.0 (at the moment for our business case we are still comfortable with 5.9) but I'm following the discussion.
> 
> If master is working as expected, i'll just tag it and release so you can stick to semantic versioning instead of refering to master; in the mean time I will not merge anything in master so it's fine for now but in the long run it is not very reliable.

@philippe-bourdeau "..in the long run it not very reliable". The package or refering to master/versionning ? 

Also as @WimDeMeester it is working with 6.0 for me (referenced master )

**Comment by philippe-bourdeau** [comment]
@devuniverse I meant relying on master branch being refered in the composer.json.

I tagged version 7.2, which supports laravel 6.0.
