### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rutiger** [zerospam/laravel-gettext#42]
I am trying to install the package via composer, in Laravel 5.5.48 but it throws me an error:

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'LaravelGettext' not found"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/immigration/immigration-frontend/vendor/zerospam/laravel-gettext/src/Xinax/LaravelGettext/Middleware/GettextMiddleware.php:25
#0 {main} in /var/www/immigration/immigration-frontend/public/index.php:0

```
Apparently it does not install all sources, any idea?

**Comment by philippe-bourdeau** [comment]
See https://github.com/zerospam/laravel-gettext/issues/27, I suspect you have the same problem.

**Comment by rutiger** [comment]
Done, clearing application cache and deleting old vendors solved the problem.
