### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by MarkusJLechner** [zerospam/laravel-gettext#45]

**Comment by WimDeMeester** [comment]
I get the following problem: 
zerospam/laravel-gettext 7.2.1 requires laravel/framework ^5.6 || ^6.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].

**Comment by michaloravec** [comment]
It would be great, if somebody merge this pull request finally.

**Comment by WimDeMeester** [comment]
I agree, but I think that only the owner of this repository can do this.

**Comment by pabloblazquez** [comment]
Please, owner, merge this fix for L7... thanks in advice!

**Comment by WimDeMeester** [comment]
If you can make me a maintainer of the repository, I can also merge the pull request.  Is there something else I need to do?

**Comment by CedNet** [comment]
Can someone just email the owner? I need to upgrade Laravel and this package stops me without another... fork.

**Comment by sukiyanen85** [comment]
Same here, can't update to v7 because of this package 

`- zerospam/laravel-gettext 7.2.1 requires laravel/framework ^5.6 || ^6.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
`

**Comment by redalpha01** [comment]
Couldn't you branch it and change the dependencies? It's not like there's many breaking changes that affect this packages.

**Comment by WimDeMeester** [comment]
That is what I did.  You can use https://github.com/DeepskyLog/laravel-gettext

**Comment by sukiyanen85** [comment]
> That is what I did. You can use https://github.com/DeepskyLog/laravel-gettext

Thank you so much! Just upgraded using your repository, since this one looks abandoned it would be great if you could keep yours updated for future Laravel versions

**Comment by WimDeMeester** [comment]
> > That is what I did. You can use https://github.com/DeepskyLog/laravel-gettext
> 
> Thank you so much! Just upgraded using your repository, since this one looks abandoned it would be great if you could keep yours updated for future Laravel versions

That is my plan!

**Comment by marcth** [comment]
In order to get `zerospam/laravel-gettext` functioning under Laravel 7.x, I created a repository with the same name as the package and defined the distribution as a zip archive pointing to the Github zip file.
```
 "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "zerospam/laravel-gettext": "^7.2"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "zerospam/laravel-gettext",
                "version": "7.2.1",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/zerospam/laravel-gettext/archive/7.2.1.zip",
                    "reference": "7.2.1"
                },
                "autoload": {
                    "classmap": ["."]
                }
            }
        }
    ],
```
In other words, I added the `repository` section above and then issued the command: `composer require zerospam/laravel-gettext` on a fresh install of Laravel 7.x with no issues.

**Comment by marcth** [comment]
I added a temporary fix to Laravel's 7.x `composer.json` file until the `zerospam/laravel-gettext` child `composer.json` file is updated. Add a `repositories` section similar to what is shown below (I just copied the laravel-gettext `composer.json` making sure to:

1. Specify the distribution as a ZIP archive pointing to the gettext git repo.
2. Update the laravel framework requirement to `"laravel/framework": "^5.6 || ^6.0 || ^7.0",`

Once the package is updated, it should just be a matter of removing the repository definition and upgrading to the latest version.

```
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "zerospam/laravel-gettext": "^7.2"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "zerospam/laravel-gettext",
                "description": "Adds localization support to laravel applications in an easy way using Poedit and GNU gettext.",
                "homepage": "https://github.com/zerospam/laravel-gettext",
                "support": {
                    "issues": "https://github.com/zerospam/laravel-gettext/issues"
                },
                "keywords": [
                    "gettext",
                    "localization",
                    "poedit",
                    "laravel-gettext",
                    "laravel",
                    "translation"
                ],
                "authors": [
                    {
                        "name": "Nicolás Daniel Palumbo",
                        "email": "n@xinax.net"
                    },
                    {
                        "name": "Antoine Aflalo",
                        "email": "dev+laravel_gettext@zerospam.ca"
                    }
                ],
                "license": "MIT",
                "version": "7.2.1",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/zerospam/laravel-gettext/archive/7.2.1.zip",
                    "reference": "7.2.1"
                },
                "require": {
                    "php": ">=7.1",
                    "laravel/framework": "^5.6 || ^6.0 || ^7.0",
                    "laravel/helpers": "^1.1"
                },
                "require-dev": {
                    "mockery/mockery": "dev-master",
                    "phpunit/phpunit": "~7.0 || ^8",
                    "squizlabs/php_codesniffer": "1.5.*",
                    "laravel/laravel": "^5.6 || ^6.0",
                    "php-coveralls/php-coveralls": "^2.1"
                },
                "autoload": {
                    "psr-0": {
                        "Xinax\\LaravelGettext\\": "src/"
                    },
                    "files": [
                        "src/Xinax/LaravelGettext/Support/helpers.php"
                    ]
                },
                "minimum-stability": "stable",
                "extra": {
                    "laravel": {
                        "providers": [
                            "Xinax\\LaravelGettext\\LaravelGettextServiceProvider"
                        ]
                    }
                }
            }
        }
    ],
```

**Comment by philippe-bourdeau** [comment]
Upcoming release will support up to laravel 8.
