### ISSUE TITLE
Can't install on laravel 6.18

### ISSUE THREAD

**Issue by karpovigorok** [zerospam/laravel-gettext#47]
Hi,

Do you need to change composer.json on your side?

**Comment by nekhbet** [comment]
Any solution? Thanks!

**Comment by nekhbet** [comment]
@karpovigorok try with 
"zerospam/laravel-gettext": "@dev"
in your composer.json

**Comment by karpovigorok** [comment]
> @karpovigorok try with
> "zerospam/laravel-gettext": "@dev"
> in your composer.json

thank you for suggestion
