### ISSUE TITLE
7.1 FileSystem.php:300 Passing glue string after array is deprecated php 7.4

### ISSUE THREAD

**Issue by atlasan** [zerospam/laravel-gettext#59]
Hi!
I am using version 7.1 with laravel 5.7 and php 7.4.8 and getting and error:
`FileSystem.php:300 = implode(): Passing glue string after array is deprecated. Swap the parameters`

After checking it seems that it is safe to use implode with the correct reverse order:
`implode(DIRECTORY_SEPARATOR, $data)`
This has to be fixed inside FileSystem.php and GettextCreate.php (and more?)

**Comment by ruaq** [comment]
This repo wasn’t maintained for months and PHP 7.4 is also EOL. See https://www.php.net/supported-versions.php

https://github.com/nekhbet/laravel-gettext seems to be an active fork for the future, but you’ll have to update your Versions. :wink:

**Comment by atlasan** [comment]
^_^ thanks you @ruaq
